name: marj_logger
description: "A wrapper over the talker_flutter package to help with consol logging."
version: 0.0.1

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  talker_dio_logger: ^4.1.3
  talker_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
